import {ToolLoopAgent, stepCountIs, tool} from 'ai';
import {z} from 'zod';
import {streamSubAgent, AiSliceState} from '@sqlrooms/ai-core';
import {StoreApi} from '@sqlrooms/room-store';
import {KeplerContext} from '../types';
import {getGeoTools} from '../tools/geo-tools';
import {getQueryTools} from '../tools/query-tool';
import {getDuckdbTableContext} from '../tools/duckdb-cache';
import {getModel} from './model-utils';

const GEO_AGENT_INSTRUCTIONS = `You are a geospatial analysis assistant. You help users with spatial operations, geocoding, routing, and geographic data processing.

For spatialQuery tool:
1. Use DuckDB spatial SQL syntax with ST_* functions (ST_Intersects, ST_Within, ST_Buffer, ST_Centroid, ST_Union_Agg, ST_Length, ST_Area, ST_Perimeter, ST_AsGeoJSON, ST_GeomFromGeoJSON).
2. The geometry column stores GeoJSON strings — always wrap with ST_GeomFromGeoJSON(geometry) for spatial ops.
3. Reference tables using __tbl0__, __tbl1__, ... placeholders (mapped to datasetNames in order).
4. When outputting geometry, use ST_AsGeoJSON(...) AS geometry to keep results as GeoJSON strings.

For any SQL query:
1. Only use statements, query syntax, data types, expressions, functions that are supported by DuckDB.
2. Use __TABLE__ as the table name placeholder in SQL queries. It will be replaced with the actual DuckDB table name at runtime.
3. Only first 2 rows of the result will be returned to LLM for reference.

For data analysis:
1. If new dataset has been generated by tools (spatialQuery, isochrone, etc.):
   a. Save them as a new dataset in kepler.gl first
   b. Use the new dataset for spatial analysis
2. For using road datasets in spatial analysis:
   a. Buffer the road by 1 meter first using spatialQuery
   b. Save the buffered road as a new dataset

For dataClassify tool: when classifying data into bins:
a. The lower bound is inclusive, and the upper bound is exclusive except the last bin
b. If user provides custom breaks, there is no need to call dataClassify tool

For datasetName argument:
1. Use the dataset name or dataset label, not the dataset id
`;

export function geoAgentTool(store: StoreApi<AiSliceState>, ctx: KeplerContext) {
  return tool({
    description:
      'An agent for geospatial analysis: routing, isochrones, geocoding, spatial queries (join, filter, buffer, centroid, dissolve, area, length, perimeter via DuckDB spatial SQL), grid, Voronoi, MST, cartogram, US boundary data, and other geo operations.',
    inputSchema: z.object({
      reasoning: z.string().describe('Reasoning for why this agent is being called'),
      prompt: z.string().describe('The geospatial analysis request')
    }),
    execute: async ({prompt}, options?: {toolCallId?: string; abortSignal?: AbortSignal}) => {
      const geoTools = getGeoTools(ctx);
      const queryTools = getQueryTools(ctx);
      const tools = {
        ...geoTools,
        ...queryTools
      };
      const tableContext = await getDuckdbTableContext();
      const instructions = tableContext
        ? `${GEO_AGENT_INSTRUCTIONS}\n${tableContext}`
        : GEO_AGENT_INSTRUCTIONS;

      const agent = new ToolLoopAgent({
        model: getModel(store),
        instructions,
        tools,
        stopWhen: stepCountIs(15)
      });

      const result = await streamSubAgent(
        agent,
        prompt,
        store,
        options?.toolCallId || '',
        options?.abortSignal
      );

      return {
        success: true,
        finalOutput: result.finalOutput
      };
    }
  });
}
